#!/bin/bash

sudo pacman -S base-devel cmake unzip ninja curl
git clone -b stable https://github.com/neovim/neovim $HOME/repos/neovim
cd $HOME/repos/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
